# copyright 2015 J. Maurice <j@wiz.biz>

require '..'

wiz.package 'wiz.framework.util.world'

class wiz.framework.util.world.regions
	@AS: 'Asia'
	@EU: 'Europe'
	@AF: 'Africa'
	@OC: 'Oceania'
	@NA: 'North America'
	@ZZ: 'Undefined'

class wiz.framework.util.world.countries

	@AS: #{{{
		AF: 'Afghanistan'
		AM: 'Armenia'
		AZ: 'Azerbaijan'
		BH: 'Bahrain'
		BD: 'Bangladesh'
		BT: 'Bhutan'
		BN: 'Brunei Darussalam'
		KH: 'Cambodia'
		CN: 'China'
		CY: 'Cyprus'
		GE: 'Georgia'
		HK: 'Hong Kong'
		IN: 'India'
		ID: 'Indonesia'
		IR: 'Iran, Islamic Republic of'
		IQ: 'Iraq'
		IL: 'Israel'
		JP: 'Japan'
		JO: 'Jordan'
		KZ: 'Kazakhstan'
		KP: 'Korea, Democratic People\'s Republic of'
		KR: 'Korea, Republic of'
		KW: 'Kuwait'
		KG: 'Kyrgyzstan'
		LA: 'Lao People\'s Democratic Republic'
		LB: 'Lebanon'
		MO: 'Macao'
		MY: 'Malaysia'
		MV: 'Maldives'
		MN: 'Mongolia'
		MM: 'Myanmar'
		NP: 'Nepal'
		OM: 'Oman'
		PK: 'Pakistan'
		PS: 'Palestine, State of'
		PH: 'Philippines'
		QA: 'Qatar'
		SA: 'Saudi Arabia'
		SG: 'Singapore'
		LK: 'Sri Lanka'
		SY: 'Syrian Arab Republic'
		TW: 'Taiwan, Province of China'
		TJ: 'Tajikistan'
		TH: 'Thailand'
		TL: 'Timor-Leste'
		TR: 'Turkey'
		TM: 'Turkmenistan'
		AE: 'United Arab Emirates'
		UZ: 'Uzbekistan'
		VN: 'Viet Nam'
		YE: 'Yemen'
	#}}}
	@EU: #{{{
		AX: 'Åland Islands'
		AL: 'Albania'
		AD: 'Andorra'
		AT: 'Austria'
		BY: 'Belarus'
		BE: 'Belgium'
		BA: 'Bosnia and Herzegovina'
		BG: 'Bulgaria'
		HR: 'Croatia'
		CZ: 'Czech Republic'
		DK: 'Denmark'
		EE: 'Estonia'
		FO: 'Faroe Islands'
		FI: 'Finland'
		FR: 'France'
		DE: 'Germany'
		GI: 'Gibraltar'
		GR: 'Greece'
		GG: 'Guernsey'
		VA: 'Holy See (Vatican City State)'
		HU: 'Hungary'
		IS: 'Iceland'
		IE: 'Ireland'
		IM: 'Isle of Man'
		IT: 'Italy'
		JE: 'Jersey'
		LV: 'Latvia'
		LI: 'Liechtenstein'
		LT: 'Lithuania'
		LU: 'Luxembourg'
		MK: 'Macedonia, the former Yugoslav Republic of'
		MT: 'Malta'
		MD: 'Moldova, Republic of'
		MC: 'Monaco'
		ME: 'Montenegro'
		NL: 'Netherlands'
		NO: 'Norway'
		PL: 'Poland'
		PT: 'Portugal'
		RO: 'Romania'
		RU: 'Russian Federation'
		SM: 'San Marino'
		RS: 'Serbia'
		SK: 'Slovakia'
		SI: 'Slovenia'
		ES: 'Spain'
		SJ: 'Svalbard and Jan Mayen'
		SE: 'Sweden'
		CH: 'Switzerland'
		UA: 'Ukraine'
		GB: 'United Kingdom'
	#}}}
	@AF: #{{{
		DZ: 'Algeria'
		AO: 'Angola'
		BJ: 'Benin'
		BW: 'Botswana'
		BF: 'Burkina Faso'
		BI: 'Burundi'
		CM: 'Cameroon'
		CV: 'Cape Verde'
		CF: 'Central African Republic'
		TD: 'Chad'
		KM: 'Comoros'
		CG: 'Congo'
		CD: 'Congo, the Democratic Republic of the'
		CI: 'Côte d\'Ivoire'
		DJ: 'Djibouti'
		EG: 'Egypt'
		GQ: 'Equatorial Guinea'
		ER: 'Eritrea'
		ET: 'Ethiopia'
		GA: 'Gabon'
		GM: 'Gambia'
		GH: 'Ghana'
		GN: 'Guinea'
		GW: 'Guinea-Bissau'
		KE: 'Kenya'
		LS: 'Lesotho'
		LR: 'Liberia'
		LY: 'Libya'
		MG: 'Madagascar'
		MW: 'Malawi'
		ML: 'Mali'
		MR: 'Mauritania'
		MU: 'Mauritius'
		YT: 'Mayotte'
		MA: 'Morocco'
		MZ: 'Mozambique'
		NA: 'Namibia'
		NE: 'Niger'
		NG: 'Nigeria'
		RE: 'Réunion'
		RW: 'Rwanda'
		SH: 'Saint Helena, Ascension and Tristan da Cunha'
		ST: 'Sao Tome and Principe'
		SN: 'Senegal'
		SC: 'Seychelles'
		SL: 'Sierra Leone'
		SO: 'Somalia'
		ZA: 'South Africa'
		SS: 'South Sudan'
		SD: 'Sudan'
		SZ: 'Swaziland'
		TZ: 'Tanzania, United Republic of'
		TG: 'Togo'
		TN: 'Tunisia'
		UG: 'Uganda'
		EH: 'Western Sahara'
		ZM: 'Zambia'
		ZW: 'Zimbabwe'
		#}}}
	@OC: #{{{
		AS: 'American Samoa'
		AU: 'Australia'
		CK: 'Cook Islands'
		FJ: 'Fiji'
		PF: 'French Polynesia'
		GU: 'Guam'
		KI: 'Kiribati'
		MH: 'Marshall Islands'
		FM: 'Micronesia, Federated States of'
		NR: 'Nauru'
		NC: 'New Caledonia'
		NZ: 'New Zealand'
		NU: 'Niue'
		NF: 'Norfolk Island'
		MP: 'Northern Mariana Islands'
		PW: 'Palau'
		PG: 'Papua New Guinea'
		PN: 'Pitcairn'
		WS: 'Samoa'
		SB: 'Solomon Islands'
		TK: 'Tokelau'
		TO: 'Tonga'
		TV: 'Tuvalu'
		VU: 'Vanuatu'
		WF: 'Wallis and Futuna'
	#}}}
	@NA: #{{{
		AI: 'Anguilla'
		AG: 'Antigua and Barbuda'
		AR: 'Argentina'
		AW: 'Aruba'
		BS: 'Bahamas'
		BB: 'Barbados'
		BZ: 'Belize'
		BM: 'Bermuda'
		BO: 'Bolivia, Plurinational State of'
		BQ: 'Bonaire, Sint Eustatius and Saba'
		BR: 'Brazil'
		CA: 'Canada'
		KY: 'Cayman Islands'
		CL: 'Chile'
		CO: 'Colombia'
		CR: 'Costa Rica'
		CU: 'Cuba'
		CW: 'Curaçao'
		DM: 'Dominica'
		DO: 'Dominican Republic'
		EC: 'Ecuador'
		SV: 'El Salvador'
		FK: 'Falkland Islands (Malvinas)'
		GF: 'French Guiana'
		GL: 'Greenland'
		GD: 'Grenada'
		GP: 'Guadeloupe'
		GT: 'Guatemala'
		GY: 'Guyana'
		HT: 'Haiti'
		HN: 'Honduras'
		JM: 'Jamaica'
		MQ: 'Martinique'
		MX: 'Mexico'
		MS: 'Montserrat'
		NI: 'Nicaragua'
		PA: 'Panama'
		PY: 'Paraguay'
		PE: 'Peru'
		PR: 'Puerto Rico'
		BL: 'Saint Barthélemy'
		KN: 'Saint Kitts and Nevis'
		LC: 'Saint Lucia'
		MF: 'Saint Martin (French part)'
		PM: 'Saint Pierre and Miquelon'
		VC: 'Saint Vincent and the Grenadines'
		SX: 'Sint Maarten (Dutch part)'
		SR: 'Suriname'
		TT: 'Trinidad and Tobago'
		TC: 'Turks and Caicos Islands'
		US: 'United States'
		UY: 'Uruguay'
		VE: 'Venezuela, Bolivarian Republic of'
		VG: 'Virgin Islands, British'
		VI: 'Virgin Islands, U.S.'
	#}}}
	@ZZ: #{{{
		AQ: 'Antarctica'
		BV: 'Bouvet Island'
		IO: 'British Indian Ocean Territory'
		CX: 'Christmas Island'
		CC: 'Cocos (Keeling) Islands'
		TF: 'French Southern Territories'
		HM: 'Heard Island and McDonald Islands'
		GS: 'South Georgia and the South Sandwich Islands'
		UM: 'United States Minor Outlying Islands'
	#}}}

# vim: foldmethod=marker wrap
